dbstop if error
clear
clc
symbols = {'MMM', 'ABT', 'ABBV', 'ACN', 'ATVI', 'ADBE',...
           'AMD', 'AAP', 'AES', 'AMG', 'AFL', 'A', 'APD', 'AKAM', 'ALK',...
           'ALB', 'ARE', 'ALXN', 'ALGN', 'ALLE', 'AGN', 'ADS', 'LNT', 'ALL',...
           'GOOGL', 'GOOG', 'MO', 'AMZN', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG',...
           'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'APC', 'ADI',...
           'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'AIV', 'AAPL', 'AMAT', 'APTV',...
           'ADM', 'ARNC', 'AJG', 'AIZ', 'T', 'ADSK', 'ADP', 'AZO',...
           'AVB', 'AVY', 'BHGE', 'BLL', 'BAC', 'BK', 'BAX', 'BDX',...
           'BRK-B', 'BBY', 'BIIB', 'BLK', 'HRB', 'BA', 'BKNG', 'BWA', 'BXP',...
           'BSX', 'BMY', 'AVGO', 'BF-B', 'CHRW', 'COG', 'CDNS', 'CPB',...
           'COF', 'CPRI', 'CAH', 'KMX', 'CCL', 'CAT', 'CBOE', 'CBRE', 'CBS',...
           'CELG', 'CNC', 'CNP', 'CTL', 'CERN', 'SCHW', 'CHTR',...
           'CVX', 'CMG', 'CB', 'CHD', 'CI', 'XEC', 'CINF', 'CTAS', 'CSCO',...
           'C', 'CFG', 'CTXS', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA',...
           'CMA', 'CAG', 'CXO', 'COP', 'ED', 'STZ', 'COO', 'GLW',...
           'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE',...
           'DAL', 'XRAY', 'DVN', 'DLR', 'DFS', 'DISCA', 'DISCK', 'DISH',...
           'DG', 'DLTR', 'D', 'DOV', 'DWDP', 'DTE', 'DRE', 'DUK', 'DXC',...
           'ETFC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EA', 'ETR',...
           'EOG', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ES', 'RE', 'EXC',...
           'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS',...
           'FITB', 'FE', 'FISV', 'FLIR', 'FLS', 'FLR', 'FMC', 'FL',...
           'F', 'FTV', 'FBHS', 'FOXA', 'FOX', 'BEN', 'FCX', 'GPS', 'GRMN',...
           'IT', 'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GS', 'GWW', 'HAL',...
           'HBI', 'HOG', 'HRS', 'HAS', 'HCA', 'HCP', 'HP', 'HSIC', 'HSY',...
           'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HPQ',...
           'HUM', 'HBAN', 'IDXX', 'INFO', 'ITW', 'ILMN', 'IR', 'INTC',...
           'ICE', 'IBM', 'INCY', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ',...
           'IQV', 'IRM', 'JEC', 'JBHT', 'SJM',...
           'JCI', 'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'KMB', 'KIM', 'KMI',...
           'KLAC', 'KSS', 'KHC', 'KR', 'LB', 'LLL', 'LH', 'LRCX', 'LEG',...
           'LEN', 'LLY', 'LNC', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB',...
           'MAC', 'M', 'MRO', 'MPC', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MAT',...
           'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'MET', 'MTD', 'MGM', 'MCHP',...
           'MU', 'MSFT', 'MAA', 'MHK', 'TAP', 'MDLZ', 'MNST', 'MCO', 'MS', 'MOS',...
           'MSI', 'MYL', 'NDAQ', 'NOV', 'NTAP', 'NFLX', 'NWL',...
           'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NBL', 'JWN', 'NSC',...
           'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'ORLY', 'OXY', 'OMC',...
           'ORCL', 'PCAR', 'PKG', 'PH', 'PAYX', 'PYPL', 'PNR', 'PBCT', 'PEP', 'PKI',...
           'PRGO', 'PFE', 'PM', 'PXD', 'PNC', 'RL', 'PPL', 'PFG', 'PG',...
           'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 'PVH', 'QRVO', 'PWR', 'QCOM',...
           'RJF', 'RTN', 'O', 'RHT', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI',...
           'ROK', 'ROP', 'ROST', 'RCL', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE',...
           'SRE', 'SHW', 'SPG', 'SWKS', 'SLG', 'SNA', 'SO', 'LUV', 'SPGI', 'SWK',...
           'SBUX', 'STT', 'SYK', 'STI', 'SYMC', 'SYF', 'SNPS', 'SYY', 'TROW',...
           'TPR', 'TGT', 'TEL', 'FTI', 'TXN', 'TXT', 'TMO', 'TIF',...
           'TJX', 'TMK', 'TSS', 'TSCO', 'TDG', 'TRV', 'TRIP', 'TSN', 'UDR',...
           'ULTA', 'USB', 'UAA', 'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UTX', 'UHS',...
           'UNM', 'VFC', 'VLO', 'VAR', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VIAB',...
           'V', 'VNO', 'WMT', 'WBA', 'DIS', 'WM', 'WAT', 'WEC',...
           'WFC', 'WELL', 'WDC', 'WU', 'WRK', 'WY', 'WHR', 'WMB', 'WLTW', 'WYNN',...
           'XEL', 'XRX', 'XLNX', 'XYL', 'YUM', 'ZION', 'ZTS'};
disp('Request historical S&P 500 companies price');
initDate = '1-Jan-2018';
endDate = '10-May-2019';
interval = '1d';
DataMat = [];
for i = 1:length(symbols)
    gspc = getMData(symbols{i}, initDate, endDate, interval);
    disp(i)
    gspc = table2struct(gspc);
    if size(gspc, 1) == 340
        DataMat = [DataMat, gspc];
    else
        disp(symbols{i})
    end
end
gspc = getMData('^GSPC', initDate, endDate, interval);
gspc = table2struct(gspc);
save('MarketSP500')